apiVersion: v1
kind: ResourceQuota
metadata:
  name: fastapi-app-quota
  namespace: fastapi-app
spec:
  hard:
    # Compute
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    # Workloads
    pods: "20"
    # Services
    services: "5"
    services.loadbalancers: "1"
    services.nodeports: "0"
    # Storage
    persistentvolumeclaims: "5"
    requests.storage: 10Gi
    # Config & Secrets
    configmaps: "10"
    secrets: "10"
