apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fastapi-dev

resources:
  - ../../base

namePrefix: dev-

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "50m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "64Mi"
    target:
      kind: Deployment
      name: fastapi-app

configMapGenerator:
  - name: fastapi-config
    behavior: merge
    literals:
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
